-- ===========================================================================
-- THE GARDEN DROP — initial schema
--
-- Run this once, then run supabase/seed.sql (generated by
-- `npm run db:seed:sql`, which is scripts/generate-seed-sql.ts).
--
-- THE SHAPE, AND WHY
-- ------------------------------------------------------------------------
-- Every content table is a hybrid:
--
--   * queryable columns  — id, slug, status, updated_at, and a handful of
--     generated columns lifted out of the JSON (release_year, issue number,
--     publish_date). These exist so that SQL, indexes, RLS policies and the
--     Supabase table editor all behave the way a person would expect.
--
--   * data jsonb         — the full, typed entity exactly as it appears in
--     src/lib/types.ts. This is the record. Reads hydrate from it.
--
-- src/lib/db.ts writes `{ id, slug, status, data }` and reads back `data`.
-- If you change that contract, change it in both places.
--
-- The alternative — thirty normalised tables for six scored axes, five
-- discovery cards, an interview and an array of sources — would give a
-- two-person editorial team a migration to write every time they had an idea.
-- The jsonb column is a deliberate trade, and the generated columns are how we
-- keep the parts we actually query honest.
--
-- Relationships that are genuinely many-to-many DO get real tables:
-- issue_plants and issue_techniques, below, with foreign keys.
--
-- SAFETY
-- ------------------------------------------------------------------------
-- RLS is on for every table.
--   * anon may SELECT published content, and nothing else.
--   * anon may INSERT into subscribers, submissions and partner_enquiries,
--     and may not read a single row back out of them.
--   * service_role has BYPASSRLS, so the server (src/lib/db.ts, which uses
--     SUPABASE_SERVICE_ROLE_KEY) sees everything. That key must never reach
--     the browser.
--
-- Idempotent. Running it twice is a no-op.
-- ===========================================================================

create extension if not exists "pgcrypto";
create extension if not exists "citext";

-- ---------------------------------------------------------------------------
-- CONTENT
-- ---------------------------------------------------------------------------

-- Issues --------------------------------------------------------------------
create table if not exists public.issues (
  id           text primary key,
  slug         text unique not null,
  status       text,
  data         jsonb not null,
  updated_at   timestamptz not null default now(),

  -- Lifted out of `data` so we can order an archive without deserialising it.
  -- text->int uses int4in, which is immutable, so it is legal in a generated
  -- column. Dates are kept as ISO text for the same reason: text->date is only
  -- STABLE (it reads DateStyle) and Postgres will refuse it here. ISO-8601
  -- sorts lexicographically, so nothing is lost.
  issue_number int  generated always as (((data ->> 'number'))::int) stored,
  publish_date text generated always as ((data ->> 'publishDate')) stored
);

-- Stories -------------------------------------------------------------------
create table if not exists public.stories (
  id         text primary key,
  slug       text unique not null,
  status     text,
  data       jsonb not null,
  updated_at timestamptz not null default now(),
  issue_slug text generated always as ((data ->> 'issueSlug')) stored,
  kind       text generated always as ((data ->> 'kind')) stored
);

-- Plants --------------------------------------------------------------------
create table if not exists public.plants (
  id           text primary key,
  slug         text unique not null,
  status       text,
  data         jsonb not null,
  updated_at   timestamptz not null default now(),
  release_year int  generated always as (((data ->> 'releaseYear'))::int) stored,
  plant_type   text generated always as ((data ->> 'type')) stored,
  verdict      text generated always as ((data ->> 'verdict')) stored,
  breeder      text generated always as ((data ->> 'breeder')) stored
);

-- Techniques ----------------------------------------------------------------
create table if not exists public.techniques (
  id             text primary key,
  slug           text unique not null,
  status         text,
  data           jsonb not null,
  updated_at     timestamptz not null default now(),
  evidence_level text generated always as ((data ->> 'evidenceLevel')) stored,
  verdict        text generated always as ((data ->> 'verdict')) stored
);

-- Experts -------------------------------------------------------------------
-- No status column in the type: an expert is a person, not a publication. The
-- column exists anyway because src/lib/db.ts writes it generically; it stays
-- null, and the RLS policy below does not consult it.
create table if not exists public.experts (
  id         text primary key,
  slug       text unique not null,
  status     text,
  data       jsonb not null,
  updated_at timestamptz not null default now()
);

-- Sources -------------------------------------------------------------------
-- No slug: a source is addressed by id. Column present for the generic writer.
create table if not exists public.sources (
  id         text primary key,
  slug       text,
  status     text,
  data       jsonb not null,
  updated_at timestamptz not null default now(),
  kind       text generated always as ((data ->> 'kind')) stored,
  url        text generated always as ((data ->> 'url')) stored
);

-- Retail links --------------------------------------------------------------
create table if not exists public.retail_links (
  id         text primary key,
  slug       text,
  status     text,
  data       jsonb not null,
  updated_at timestamptz not null default now(),
  plant_slug text    generated always as ((data ->> 'plantSlug')) stored,
  vendor     text    generated always as ((data ->> 'vendor')) stored,
  affiliate  boolean generated always as (((data ->> 'affiliate'))::boolean) stored
);

-- Categories ----------------------------------------------------------------
create table if not exists public.categories (
  id         text primary key,
  slug       text unique not null,
  status     text,
  data       jsonb not null,
  updated_at timestamptz not null default now(),
  kind       text generated always as ((data ->> 'kind')) stored
);

-- Regions -------------------------------------------------------------------
create table if not exists public.regions (
  id         text primary key,
  slug       text unique not null,
  status     text,
  data       jsonb not null,
  updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- REAL RELATIONS
--
-- Plants and techniques appear in more than one issue. That is a genuine
-- many-to-many and it gets a real join table with real foreign keys, so that a
-- deleted plant cannot leave a dangling reference inside somebody's issue.
--
-- src/lib/db.ts reads the relationship from data->'issueSlugs' (which is the
-- authoritative copy, and is what the local JSON store uses). These tables are
-- kept in step by scripts/generate-seed-sql.ts and exist so that SQL can ask
-- "what was in issue 3?" without a jsonb containment scan.
-- ---------------------------------------------------------------------------

create table if not exists public.issue_plants (
  issue_slug text not null references public.issues (slug) on delete cascade on update cascade,
  plant_slug text not null references public.plants (slug) on delete cascade on update cascade,
  primary key (issue_slug, plant_slug)
);

create table if not exists public.issue_techniques (
  issue_slug     text not null references public.issues (slug)     on delete cascade on update cascade,
  technique_slug text not null references public.techniques (slug) on delete cascade on update cascade,
  primary key (issue_slug, technique_slug)
);

-- ---------------------------------------------------------------------------
-- AUDIENCE
--
-- Same hybrid shape, because src/lib/db.ts writes these through the same
-- generic insert(). The columns a human wants to filter on — email, status,
-- source, zone — are generated from the JSON. created_at is a plain column
-- with a default, because casting text to timestamptz is only STABLE and
-- Postgres will not allow it in a generated column.
-- ---------------------------------------------------------------------------

create table if not exists public.subscribers (
  id         text primary key,
  slug       text,
  status     text,
  data       jsonb not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  email      text generated always as ((data ->> 'email')) stored,
  source     text generated always as ((data ->> 'source')) stored,
  zone       text generated always as ((data ->> 'zone')) stored
);

-- One person, one row. Case-insensitive, because nobody types their own address
-- the same way twice. (citext is installed above if you would rather change the
-- column type than carry the index — this works and is cheaper.)
create unique index if not exists subscribers_email_key on public.subscribers (lower(email));

create table if not exists public.submissions (
  id           text primary key,
  slug         text,
  status       text,
  data         jsonb not null,
  updated_at   timestamptz not null default now(),
  created_at   timestamptz not null default now(),
  email        text generated always as ((data ->> 'email')) stored,
  subject_name text generated always as ((data ->> 'subjectName')) stored,
  subject_kind text generated always as ((data ->> 'subjectKind')) stored
);

create table if not exists public.partner_enquiries (
  id         text primary key,
  slug       text,
  status     text,
  data       jsonb not null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  email      text generated always as ((data ->> 'email')) stored,
  company    text generated always as ((data ->> 'company')) stored,
  interest   text generated always as ((data ->> 'interest')) stored
);

-- ---------------------------------------------------------------------------
-- INDEXES
-- ---------------------------------------------------------------------------

create index if not exists issues_status_idx        on public.issues (status);
create index if not exists issues_number_idx        on public.issues (issue_number desc);
create index if not exists issues_publish_date_idx  on public.issues (publish_date desc);

create index if not exists stories_status_idx       on public.stories (status);
create index if not exists stories_issue_slug_idx   on public.stories (issue_slug);

create index if not exists plants_status_idx        on public.plants (status);
create index if not exists plants_release_year_idx  on public.plants (release_year desc);
create index if not exists plants_type_idx          on public.plants (plant_type);
create index if not exists plants_verdict_idx       on public.plants (verdict);

create index if not exists techniques_status_idx    on public.techniques (status);
create index if not exists techniques_verdict_idx   on public.techniques (verdict);

create index if not exists retail_links_plant_idx   on public.retail_links (plant_slug);
create index if not exists sources_kind_idx         on public.sources (kind);
create index if not exists categories_kind_idx      on public.categories (kind);

create index if not exists subscribers_status_idx   on public.subscribers (status);
create index if not exists subscribers_created_idx  on public.subscribers (created_at desc);
create index if not exists submissions_status_idx   on public.submissions (status);
create index if not exists submissions_created_idx  on public.submissions (created_at desc);
create index if not exists partners_status_idx      on public.partner_enquiries (status);
create index if not exists partners_created_idx     on public.partner_enquiries (created_at desc);

create index if not exists issue_plants_plant_idx        on public.issue_plants (plant_slug);
create index if not exists issue_techniques_tech_idx     on public.issue_techniques (technique_slug);

-- The one place we really do query inside the JSON: "which issues is this
-- plant in?" A GIN index makes `data -> 'issueSlugs' @> '["03-x"]'` cheap.
create index if not exists plants_issue_slugs_idx     on public.plants     using gin ((data -> 'issueSlugs'));
create index if not exists techniques_issue_slugs_idx on public.techniques using gin ((data -> 'issueSlugs'));

-- ---------------------------------------------------------------------------
-- ROW LEVEL SECURITY
-- ---------------------------------------------------------------------------

alter table public.issues            enable row level security;
alter table public.stories           enable row level security;
alter table public.plants            enable row level security;
alter table public.techniques        enable row level security;
alter table public.experts           enable row level security;
alter table public.sources           enable row level security;
alter table public.retail_links      enable row level security;
alter table public.categories        enable row level security;
alter table public.regions           enable row level security;
alter table public.issue_plants      enable row level security;
alter table public.issue_techniques  enable row level security;
alter table public.subscribers       enable row level security;
alter table public.submissions       enable row level security;
alter table public.partner_enquiries enable row level security;

-- Published content is public. Drafts are not. This is the whole policy for
-- everything an editor writes.
drop policy if exists "published issues are public" on public.issues;
create policy "published issues are public"
  on public.issues for select to anon, authenticated
  using (status = 'published');

drop policy if exists "published stories are public" on public.stories;
create policy "published stories are public"
  on public.stories for select to anon, authenticated
  using (status = 'published');

drop policy if exists "published plants are public" on public.plants;
create policy "published plants are public"
  on public.plants for select to anon, authenticated
  using (status = 'published');

drop policy if exists "published techniques are public" on public.techniques;
create policy "published techniques are public"
  on public.techniques for select to anon, authenticated
  using (status = 'published');

-- Reference data. These carry no status because they are not publications:
-- an expert is a person, a source is a citation, a retail link is a shop, a
-- region is a map. They are only ever reachable from a published page, they
-- contain nothing private, and hiding them would break the pages that cite
-- them. So they are readable, and that is a decision, not an oversight.
drop policy if exists "experts are public" on public.experts;
create policy "experts are public"
  on public.experts for select to anon, authenticated using (true);

drop policy if exists "sources are public" on public.sources;
create policy "sources are public"
  on public.sources for select to anon, authenticated using (true);

drop policy if exists "retail links are public" on public.retail_links;
create policy "retail links are public"
  on public.retail_links for select to anon, authenticated using (true);

drop policy if exists "categories are public" on public.categories;
create policy "categories are public"
  on public.categories for select to anon, authenticated using (true);

drop policy if exists "regions are public" on public.regions;
create policy "regions are public"
  on public.regions for select to anon, authenticated using (true);

-- Join rows are only useful alongside a published issue, so gate them on one.
drop policy if exists "issue plants follow their issue" on public.issue_plants;
create policy "issue plants follow their issue"
  on public.issue_plants for select to anon, authenticated
  using (
    exists (
      select 1 from public.issues i
      where i.slug = issue_plants.issue_slug and i.status = 'published'
    )
  );

drop policy if exists "issue techniques follow their issue" on public.issue_techniques;
create policy "issue techniques follow their issue"
  on public.issue_techniques for select to anon, authenticated
  using (
    exists (
      select 1 from public.issues i
      where i.slug = issue_techniques.issue_slug and i.status = 'published'
    )
  );

-- Audience tables: write-only for the public.
--
-- Anyone may put a row in. Nobody may take one out, count them, or read one
-- back. There is deliberately no SELECT policy on any of these three tables —
-- with RLS on and no policy, the answer to every read is zero rows. That is how
-- a subscriber list stops being an enumeration endpoint.
--
-- (The app does not actually rely on these policies: /api/subscribe runs on the
-- server with the service role. They exist so that a leaked anon key is worth
-- nothing, and so that direct-from-browser inserts remain an option.)
drop policy if exists "anyone may subscribe" on public.subscribers;
create policy "anyone may subscribe"
  on public.subscribers for insert to anon, authenticated
  with check (true);

drop policy if exists "anyone may submit" on public.submissions;
create policy "anyone may submit"
  on public.submissions for insert to anon, authenticated
  with check (true);

drop policy if exists "anyone may enquire" on public.partner_enquiries;
create policy "anyone may enquire"
  on public.partner_enquiries for insert to anon, authenticated
  with check (true);

-- service_role has BYPASSRLS in Supabase, so no policy is needed for it. Every
-- admin write and every read of a draft goes through it, from the server only.

-- ---------------------------------------------------------------------------
-- GRANTS
--
-- RLS decides which rows. Grants decide whether the role may reach the table at
-- all. Both must be right. Supabase applies broad defaults; we are explicit.
-- ---------------------------------------------------------------------------

grant usage on schema public to anon, authenticated, service_role;

grant select on
  public.issues, public.stories, public.plants, public.techniques,
  public.experts, public.sources, public.retail_links,
  public.categories, public.regions,
  public.issue_plants, public.issue_techniques
to anon, authenticated;

grant insert on public.subscribers, public.submissions, public.partner_enquiries
to anon, authenticated;

grant all on all tables in schema public to service_role;
